### PR TITLE
pairtaghighlighter: Fix crash if the tag name is missing

### LINKED ISSUE #446: pairtaghighlighter: assertion 'start < end' failed
**Version Info**
Geany: 1.27-1~trusty (geany-dev/ppa)
pairtaghighlighter: 1.27-1~trusty  (geany-dev/ppa)
OS: Ubuntu 14.04.4 LTS
LANG=id_ID.UTF-8

**GDB Output**
```
$ gdb /usr/bin/geany 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/geany...(no debugging symbols found)...done.
(gdb) run -v
Starting program: /usr/bin/geany -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Geany-INFO: Geany 1.27, id_ID.UTF-8
Geany-INFO: GTK 2.24.23, GLib 2.40.2
Geany-INFO: System data dir: /usr/share/geany
Geany-INFO: User config dir: /home/bayuah/.config/geany
[New Thread 0x7fffed7fe700 (LWP 22114)]
[New Thread 0x7fffecffd700 (LWP 22115)]
[New Thread 0x7fffe7fff700 (LWP 22116)]
[New Thread 0x7fffe77fe700 (LWP 22117)]
Geany-INFO: System plugin path: /usr/lib/x86_64-linux-gnu/geany
Geany-INFO: Added filetype CUDA (61).
Geany-INFO: Added filetype Clojure (62).
Geany-INFO: Added filetype Scala (63).
Geany-INFO: Added filetype Cython (64).
Geany-INFO: Added filetype Genie (65).
Geany-INFO: Added filetype JSON (66).
Geany-INFO: Added filetype Graphviz (67).
Geany-INFO: Loaded:   /usr/lib/x86_64-linux-gnu/geany/pairtaghighlighter.so (Pair Tag Highlighter)
Geany-INFO: /home/bayuah/anu.php : PHP (UTF-8)
Geany-INFO: Loaded /usr/share/geany/php.tags (PHP), 10122 symbol(s).
[Thread 0x7fffe7fff700 (LWP 22116) exited]

(geany:22102): Geany-CRITICAL **: sci_get_contents_range: assertion 'start < end' failed

Program received signal SIGSEGV, Segmentation fault.
__strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
209	../sysdeps/x86_64/multiarch/../strcmp.S: Tidak ada berkas atau direktori seperti itu.
(gdb) quit
```
With UBUNTU_MENUPROXY=0

```
$ export UBUNTU_MENUPROXY=0
$ gdb /usr/bin/geany 
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/geany...(no debugging symbols found)...done.
(gdb) run -v
Starting program: /usr/bin/geany -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Geany-INFO: Geany 1.27, id_ID.UTF-8
Geany-INFO: GTK 2.24.23, GLib 2.40.2
Geany-INFO: System data dir: /usr/share/geany
Geany-INFO: User config dir: /home/bayuah/.config/geany
[New Thread 0x7fffed7fe700 (LWP 23268)]
[New Thread 0x7fffecffd700 (LWP 23269)]
[New Thread 0x7fffe7fff700 (LWP 23270)]
[New Thread 0x7fffe77fe700 (LWP 23271)]
Geany-INFO: System plugin path: /usr/lib/x86_64-linux-gnu/geany
Geany-INFO: Added filetype CUDA (61).
Geany-INFO: Added filetype Clojure (62).
Geany-INFO: Added filetype Scala (63).
Geany-INFO: Added filetype Cython (64).
Geany-INFO: Added filetype Genie (65).
Geany-INFO: Added filetype JSON (66).
Geany-INFO: Added filetype Graphviz (67).
Geany-INFO: Loaded:   /usr/lib/x86_64-linux-gnu/geany/pairtaghighlighter.so (Pair Tag Highlighter)
Geany-INFO: /home/bayuah/anu.php : PHP (UTF-8)
Geany-INFO: Loaded /usr/share/geany/php.tags (PHP), 10122 symbol(s).
[Thread 0x7fffe7fff700 (LWP 23270) exited]

(geany:23260): Geany-CRITICAL **: sci_get_contents_range: assertion 'start < end' failed

Program received signal SIGSEGV, Segmentation fault.
__strcmp_ssse3 () at ../sysdeps/x86_64/multiarch/../strcmp.S:209
209	../sysdeps/x86_64/multiarch/../strcmp.S: Tidak ada berkas atau direktori seperti itu.
(gdb) quit
```

**anu.php**
```
<a id="page-number-label" class="page-link">
	1
</a>
```
**Event**
Crash happen when I tried to delete letter "a" at opening anchor (a) tag.

**Additional**
"Tidak ada berkas atau direktori seperti itu."  (Indonesian) meaning: "No such file or directory."

### PR DESCRIPTION
**Pull request by b4n**
Fixes #446 and #442.

### CODE REVIEW

**Comment by b4n** [comment]
@vmkononenko

File: pairtaghighlighter/src/pair_tag_highlighter.c [hunk 1]
```diff
@@ -169,8 +169,10 @@ static gboolean is_tag_empty(gchar *tagName)
     const char *emptyTags[] = {"area", "base", "br", "col", "embed",
                          "hr", "img", "input", "keygen", "link", "meta",
                          "param", "source", "track", "wbr", "!DOCTYPE"};
-
```
Comment (codebrainz) [inline pairtaghighlighter/src/pair_tag_highlighter.c]: Pointless change (I'm only joking, because you always call people on these :)

File: pairtaghighlighter/src/pair_tag_highlighter.c [hunk 2]
```diff
@@ -233,7 +235,7 @@ static void findMatchingOpeningTag(ScintillaObject *sci, gchar *tagName, gint op
             gchar *matchingTagName = get_tag_name(sci, matchingOpeningBracket,
                                                   matchingClosingBracket,
                                                   isMatchingTagOpening);
-            if(strcmp(tagName, matchingTagName) == 0)
+            if(matchingTagName && strcmp(tagName, matchingTagName) == 0)
```
Comment (codebrainz) [inline pairtaghighlighter/src/pair_tag_highlighter.c]: Or it could use `g_strcmp0()`.

File: pairtaghighlighter/src/pair_tag_highlighter.c [hunk 3]
```diff
@@ -319,6 +321,9 @@ static void findMatchingTag(ScintillaObject *sci, gint openingBracket, gint clos
     gboolean isTagOpening = is_tag_opening(sci, openingBracket);
     gchar *tagName = get_tag_name(sci, openingBracket, closingBracket, isTagOpening);
 
+    if (!tagName)
```
Comment (codebrainz) [inline pairtaghighlighter/src/pair_tag_highlighter.c]: I'm not familiar with this plugin's code, is it acceptable to silently fail here?

**Comment by codebrainz** [comment]
Nice work tracking this down!

File: pairtaghighlighter/src/pair_tag_highlighter.c (hunk 3 above)
Comment (vmkononenko) [inline pairtaghighlighter/src/pair_tag_highlighter.c]: In current implementation this check is redundant, because findMatchingTag() call is under the check and it is not invoked on empty brackets. 

If you prefer to have this check for safety, I would follow plugin's normal behavior: when pair is not found, original tag should be highlighted with NONMATCHING_PAIR_COLOR.

**Comment by vmkononenko** [comment]
@b4n, thanks for the fix. I even got a bugreport for that and was about to fix myself :)
I tested this change with and without check for NULL tagName in findMatchingTag(). Both work.

File: pairtaghighlighter/src/pair_tag_highlighter.c (hunk 3 above)
Comment (b4n) [inline pairtaghighlighter/src/pair_tag_highlighter.c]: The check is not redundant because it checks for `NULL`ness of `tagName`, which neither `is_tag_empty()` nor `findMatchingClosingTag()` nor `findMatchingOpeningTag()` accept.
If you want to can replace with with `tagName ? tagName : ""` or similar as argument to those functions.

And regarding the behavior, does it matter much as we're talking about a tag with no name, which is obviously invalid?  But I don't mind at all a better fix, please improve if you like :)

Comment (vmkononenko) [inline pairtaghighlighter/src/pair_tag_highlighter.c]: Why I am saying it is redundant - in current implementation of get_tag_name NULL will be returned on empty tag. And check on line 369 preserves from it (marked with comment "Don't run search on empty brackets").

But I don't mind having extra safety check, especially if something changes in future.

Comment (b4n) [inline pairtaghighlighter/src/pair_tag_highlighter.c]: > And check on line 369 preserves from it (marked with comment "Don't run search on empty brackets").

Oh.  It's not sufficient with something like `< href="foo">` as the brackets won't technically be empty (so the check you're talking about will pass), but `get_tag_name()` will return NULL.  And boom might happen (`is_tag_empty()` receiving `NULL`, or `strcmp()` alike -- but `strcmp()` doesn't have the debugging safeguard).

Comment (vmkononenko) [inline pairtaghighlighter/src/pair_tag_highlighter.c]: You're right, agree.

**Comment by frlan** [comment]
So ready to merge? ;)

**Comment by vmkononenko** [comment]
No objections from my side )
