### PR TITLE
Connect button-press signal handlers on plugin activation

### LINKED ISSUE #638: Addons: mark all not working
@eht16 When enabled "Mark all occurances of a word when double clicking it" no longer works.  (Fairly recent Git Geany and G-P GTK-3).  There have been various discussions and pull requests around the operation of finds mark all functionality IIRC, did something there break addons?

### PR DESCRIPTION
**Pull request by eht16**
If the plugin gets activated *after* Geany has been started already,
we need to iterate all open documents and attach the "button-press"
signal handler.

Fixes #638.

### CODE REVIEW

**Comment by frlan** [comment]
Not sure wether it's layer 8 issue but when deactivating the plugin again, it's still marking

File: addons/src/ao_markword.c [hunk 1]
```diff
@@ -78,6 +79,13 @@ static void ao_mark_word_set_property(GObject *object, guint prop_id,
 	{
 		case PROP_ENABLE_MARKWORD:
 			priv->enable_markword = g_value_get_boolean(value);
+			/* if the plugin is loaded while Geany is already running, we need to connect the
+			 * button press signal for open documents, if Geany is just booting,
+			 * it happens automatically */
+			if (main_is_realized())
```
Comment (b4n) [inline addons/src/ao_markword.c]: shouldn't this check for `priv->enable_markword` too, not to do that on deactivation as well?

Comment (eht16) [reply addons/src/ao_markword.c]: Uhhh, of course, thanks. Stupid me. Fixed in 71e26d8f69092ddaa2da305bb3cee4f76378a8b5.

**Comment by eht16** [comment]
@frlan details on reproducing? Even without 71e26d8f69092ddaa2da305bb3cee4f76378a8b5 it doesn't mark anything after deactivation.

**Comment by frlan** [comment]
Hmmm. Weird. I'm pretty sure I tested it with a clean version. Will retest it with latest HEAD of that branch later and give feedback. Maybe just another layer 8 issue on my end :(

**Comment by frlan** [comment]
Ah... Was an issue with automark-plugin.
