### PR TITLE
GeanyLua: Fix geany.activate()

### LINKED ISSUE #1229: [GeanyLua] geany.activate not activating document
`geany.activate()` is supposed activate a document and return true.  If it is unable, it returns false.  However, it is not activating the document.  Accepted arguments are a tab id (negative numbers), document id (positive numbers), or full document path.  Test code attempting to call `geany.activate()` with the document id (test1) and path (test2) follows:
```
  test1 = geany.activate(geany.documents(geany.filename()))

  doc_id = geany.documents(geany.filename())
  test2 = geany.activate(doc_id)

  for key,val in pairs({ test1, test2 }) do
    if val then
      geany.status("true")
    else
      geany.status("false")
      geany.status(geany.documents(geany.filename()))
      geany.status(geany.filename())
    end
  end
```
Results in status window are:
```
false
1
/tmp/test
false
1
/tmp/test
```

For reference, an excerpt from the GeanyLua [documentation](https://plugins.geany.org/geanylua/geanylua-ref.html#activate):

> **`geany.activate ( tab_id )`**
>
> Activates the document specified by tab_id.
>
> If `tab_id` is a number, it activates the document at that index.   A positive number refers to the internal document array, and a negative number refers to the (absolute) GtkNotebook index.  
> Note that the indices begin at (1) and (-1) respectively.
>
> If `tab_id` is a string, the function will try to activate the notebook tab whose filename matches that string.  
> ( The full pathname is required! )
>
> Returns `true` on success, or `false` if the tab could not be found.

### PR DESCRIPTION
**Pull request by xiota**
Resolves #1229.

### CODE REVIEW

**Comment by elextr** [comment]
LGBI and :+1: for fixing the doc.

**Comment by Skif-off** [comment]
Forgive my curiosity :) Why not
```c
if (tab_idx >= 0) {
	if (tab_idx != gtk_notebook_get_current_page(NOTEBOOK)) {
		gtk_notebook_set_current_page(NOTEBOOK, tab_idx);
	}
}
```
?

**Comment by xiota** [comment]
I haven't looked at this in a while.  Behavior originally intended is to "Actvate and focus" a document.  The original inner conditional `if (idx != ...)` prevented both.  Also, `gtk_notebook_set_current_page` most likely already performs necessary checks, so additional checks wastes processor cycles to produce incorrect behavior.

**Comment by xiota** [comment]
Confirmed original issue described in #1229 and this PR fixes it.  Used `list-open-files.lua` to test.

Force pushed to rebase.  Also corrected `> 0` to `>= 0`.  I had misunderstood @Skif-off's previous comment.

@b4n Should be ready for review and merge.

**Comment by Skif-off** [comment]
Any news?
In fact, the plugin is broken, because one of its functions is not working (maybe this is not the main function, but then what is the main function? :))).

**Comment by xiota** [comment]
> the plugin is broken, because one of its functions is not working

Anything that needs changes to this PR?

> Any news?

I'm waiting for someone to review and commit.  Maybe @frlan or @elextr ?

**Comment by Skif-off** [comment]
@xiota I meant `geany.activate()`, this function is still broken in upstream.

> I'm waiting for someone to review and commit.

Yes, I understand, I just thought that an extra reminder in notifications would remind contributors once again about the unresolved issue. And I hope I wasn't too annoying :))

**Comment by xiota** [comment]
@Skif-off No problem.  Might help to have additional confirmation that this PR is working as expected.  You've tested it after the rebase?

**Comment by Skif-off** [comment]
> You've tested it after the rebase?

Hmm... I thought you tested it. Joke :))
I am not a contributor, so my voice has little weight, but just in case I compiled and tested it 20 minutes ago: works fime, I didn't find any problems.

**Comment by xiota** [comment]
> my voice has little weight ... I didn't find any problems.

Thanks for testing.  Helpful to for you to have checked in case I miss something else.

**Comment by Skif-off** [comment]
@b4n, can you add this to the [2.1.0](https://github.com/geany/geany-plugins/milestone/17) milestone?

I do not know when the new version of Geany is scheduled to be released, there is no alternative solution and it will be sad if all forget about this PR... :)

**Comment by xiota** [comment]
@frlan Any chance you could take a look and merge?  This fixes a bug that has been affecting at least a couple users.  Thanks.

File: geanylua/glspi_doc.c [hunk 1]
```diff
@@ -92,34 +83,51 @@ static const gchar* doc_idx_to_filename(gint idx) {
...
-			if (idx<0) { /* Negative number refers to (absolute) GtkNotebook index */
-				idx=(0-idx)-1;
-				if (idx>=gtk_notebook_get_n_pages(NOTEBOOK)) { idx=-1;}
-			} else { /* A positive number refers to the geany->documents_array index */
-				idx=doc_idx_to_tab_idx(idx-1);
+	gint lua_idx = -1;
+	gint tab_idx = -1;
+
+	if (lua_gettop(L) > 0) {
+		if (lua_isnumber(L, 1)) {
```
Comment (b4n) [inline geanylua/glspi_doc.c:93]: shouldn't that be [`lua_isinteger()`](https://www.lua.org/manual/5.4/manual.html#lua_isinteger) rather than [`lua_isnumber()`](https://www.lua.org/manual/5.4/manual.html#lua_isnumber) as it's converted using [`lua_tointeger()`](https://www.lua.org/manual/5.4/manual.html#lua_tointeger) in the body?  Note that I don't know the details, but there seem to be more difference than float vs. integer.

File: geanylua/glspi_doc.c [hunk 2]
```diff
@@ -92,34 +83,51 @@ static const gchar* doc_idx_to_filename(gint idx) {
...
-	gint idx=-1;
-	if (lua_gettop(L)>0) {
-		if (lua_isnumber(L,1)) {
-			idx=(lua_tonumber(L,1));
-			if (idx<0) { /* Negative number refers to (absolute) GtkNotebook index */
-				idx=(0-idx)-1;
-				if (idx>=gtk_notebook_get_n_pages(NOTEBOOK)) { idx=-1;}
-			} else { /* A positive number refers to the geany->documents_array index */
-				idx=doc_idx_to_tab_idx(idx-1);
+	gint lua_idx = -1;
```
Comment (b4n) [inline geanylua/glspi_doc.c:89]: The scope of `lua_idx` could be reduced, and it probably would make things a bit more clear (is that used for anything else, and what is that `-1` about while `-1` is supposed to mean "first tab"?)

File: geanylua/glspi_doc.c [hunk 3]
```diff
@@ -92,34 +83,51 @@ static const gchar* doc_idx_to_filename(gint idx) {
...
+				tab_idx = document_get_notebook_page(documents[doc_idx]);
 			}
-
 		} else {
-			if (lua_isstring(L,1)) {
-				idx=doc_idx_to_tab_idx(filename_to_doc_idx(lua_tostring(L, 1)));
-			} else {
-				if (!lua_isnil(L,1)) { return FAIL_STR_OR_NUM_ARG(1); }
+			if (!lua_isnil(L, 1)) {
+				return FAIL_STR_OR_NUM_ARG(1);
```
Comment (b4n) [inline geanylua/glspi_doc.c:119]: that could be the last `else if` instead of an `else { if }` while you're at it.  Just nitpicking here though

File: geanylua/glspi_doc.c (hunk 2 above)
Comment (xiota) [reply geanylua/glspi_doc.c:89]: I wouldn't mind reducing scope, but I've been told changing previously established functionality should be avoided because it's unknown how many people might depend on the old behavior.

Indexing of notebook and documents array don't necessarily match, so might have to split into two separate or create a new lua function to convert between document and notebook indices.

Regarding the calculation...

-1 ⇒ first tab ⇒ 0
0 - (-1) = 1
1-1 = 0

File: geanylua/glspi_doc.c (hunk 3 above)
Comment (xiota) [reply geanylua/glspi_doc.c:119]: I can change this pending an opinion about change of scope.

File: geanylua/glspi_doc.c (hunk 2 above)
Comment (xiota) [reply geanylua/glspi_doc.c:89]: I think `lua_idx` is initialized to avoid compiler warnings / errors.  Don't think the particular value matters.

`tab_idx` has to be initialized to a negative number to ensure correct return value.

Comment (b4n) [reply geanylua/glspi_doc.c:89]: By reducing scope I just mean moving the variable declaration inside the `if (lua_isnumber(L, 1)) {}` block where it's used.

As for the initialization, the compiler probably wouldn't complain as the initial value is never used, but I get that some people like initializing everything. I just think that `-1` is a poor choice here as IIUC `-1` means something specific in the code below, while `0` would have been better as it's the only clearly invalid value for that same code.

On the end it wouldn't change anything on how this behaves, it would just make the implementation a hair clearer (IMO).

File: geanylua/glspi_doc.c (hunk 1 above)
Comment (b4n) [reply geanylua/glspi_doc.c:93]: OK. Did you check how it behaves if called with a string representing a number or a real number rather than an integer?
It's probably harmless but that might change behavior of this function with such values.

File: geanylua/glspi_doc.c (hunk 2 above)
Comment (b4n) [reply geanylua/glspi_doc.c:89]: > But since it looks like this function never behaved as intended,

It probably worked in the past but for the return value: part of the problematic code was likely "fine" before the internals of Geany's editor tabs was modified a few years ago.

Comment (xiota) [reply geanylua/glspi_doc.c:89]: That type of scope... I'll change it.  I probably just left the variable declaration where it was when I split the variable.  A lot of code in geany seems to declare variables at the beginning of functions.

File: geanylua/glspi_doc.c (hunk 1 above)
Comment (xiota) [reply geanylua/glspi_doc.c:92]: I tested with following:
```
test = geany.activate("2.6")
if (test)
then
  geany.status("geany.activate success")
else
  geany.status("geany.activate fail")
end
```
It truncates to `2`.

**Comment by xiota** [comment]
@b4n Thank you for reviewing.  I made the suggested changes.

File: geanylua/glspi_doc.c (hunk 1 above)
Comment (b4n) [reply geanylua/glspi_doc.c:92]: Which Lua version? But anyway using a string here seems horrible anyway so that's just for compatibility

Comment (b4n) [reply geanylua/glspi_doc.c:92]: BTW, unrelated to this, but it seems an awful idea to allow a string representation of a number, and then a string for the file name: this means that if the filename is e.g. `"1.2"` it's not gonna work.
Swapping the integer/string checks would be slightly incompatible but probably a future change worth considering.

Comment (xiota) [reply geanylua/glspi_doc.c:92]: Right now, geanylua supports only 5.1.  I plan to look at that after another bugfix #1397 is merged.

Comment (xiota) [reply geanylua/glspi_doc.c:92]: From comment in code and brief test, string has to be full document path to work.

Comment (b4n) [reply geanylua/glspi_doc.c:92]: Ah, OK, fair enough

**Comment by b4n** [comment]
I squashed the commits, and merged this, hopefully it's been tested well enough :)
Thanks!
