### PR TITLE
projectorganizer: Fix multiple tabs in Project Properties

### LINKED ISSUE #444: Project Organizer: Keeps adding more tabs to Project prefs dialog
I thought I had opened an issue about this already but I can't find it. The ProjectOrganizer plugin keeps adding tabs to the Project properties dialog each time it's shown and not removing them when it's closed.

geany_po_proj_dialog

### PR DESCRIPTION
**Pull request by techee**
There is a problem when there are multiple tabs added by plugins: if
on_project_dialog_open() is called and Project Organizer stores
the index of the tab and then another plugin adds a tab before the
Project Organizer's tab, then the stored index becomes invalid which
can lead to not correctly removing the tab from the dialog.

Instead store a pointer of the added tab widget and remove the widget
when the properties dialog is closed.

Fixes #444

### CODE REVIEW

File: projectorganizer/src/prjorg-main.c [hunk 1]
```diff
@@ -115,10 +115,10 @@ static void on_project_dialog_confirmed(G_GNUC_UNUSED GObject * obj, GtkWidget *
 static void on_project_dialog_close(G_GNUC_UNUSED GObject * obj, GtkWidget * notebook,
 		G_GNUC_UNUSED gpointer user_data)
 {
-	if (page_index != -1)
+	if (properties_tab)
 	{
-		gtk_notebook_remove_page(GTK_NOTEBOOK(notebook), page_index);
-		page_index = -1;
+		gtk_container_remove(GTK_CONTAINER(notebook), properties_tab);
```
Comment (b4n) [inline projectorganizer/src/prjorg-main.c]: you should probably simply destroy the widget, `gtk_widget_destroy(properties_tab)` (see [`gtk_container_remove()` docs](https://developer.gnome.org/gtk3/stable/GtkContainer.html#gtk-container-remove))

**Comment by codebrainz** [comment]
Would it be any use to add a function to the API to facilitate adding a plugin-specific tab to the Project preferences dialog? Or as @b4n mentioned on IRC, we could just re-create and delete the dialog each time.

**Comment by techee** [comment]
> Would it be any use to add a function to the API to facilitate adding a plugin-specific tab to the Project preferences dialog? Or as @b4n mentioned on IRC, we could just re-create and delete the dialog each time.

Less API is better IMO so I'd either vote for recreating the dialog as @b4n suggested or keeping things as they are.

File: projectorganizer/src/prjorg-main.c (hunk 1 above)
Comment (techee) [inline projectorganizer/src/prjorg-main.c]: One is too lazy to read the function description when gtk_container_remove() seems so self-descriptive :-). Will be fixed.
