### PR TITLE
Debugger: Fix cppcheck false positive warning

### LINKED ISSUE #1014: Debugger plugin: potential cppcheck false positive: uninitvar
cppcheck 2.2 complains about many `ifdef`s in the Debugger plugin:
```
make[5]: Leaving directory '/build/geany-plugins-1.36-1+20201013git06a38f4/debugger/src'
tpage.c:154:62: warning: Uninitialized variable: widgets [uninitvar]
   gtk_container_remove(GTK_CONTAINER(gtk_widget_get_parent(*widgets[i])), *widgets[i]);
                                                             ^
nofile:0:0: warning: Too many #ifdef configurations - cppcheck only checks 12 configurations. Use --force to check all configurations. For more details, use --enable=information. [toomanyconfigs]

make[4]: *** [Makefile:1686: check-cppcheck] Error 2
```

When we remove GTK2 code, this might resolve it.

What should we do until then?
- use `--force`?
- refactor the code?
- ignore?

This breaks the nightly builds for Debian Sid: https://www.geany.org/download/nightly-builds/.

### PR DESCRIPTION
**Pull request by eht16**
This fixes a cppcheck 2.2+ confusion about uninitialized widgets array
and also makes the code a bit more readable.
Closes #1014.

### CODE REVIEW

**Comment by eht16** [comment]
An alternative solution would be:
```c
		while (widgets[i])
		{
				g_object_ref(*(widgets[i]));
				gtk_container_remove(GTK_CONTAINER(gtk_widget_get_parent(*(widgets[i]))), *(widgets[i]));
				i++;
		}
```
to make `cppcheck` happy but I think the solution in this PR is more readable for humans.

The change in the second loop is not strictly necessary for `cppcheck` but is more consistent with the first loop where the same array is used.

File: debugger/src/tpage.c [hunk 1]
```diff
@@ -139,22 +139,23 @@ void tpage_pack_widgets(gboolean tabbed)
...
 		{
-			g_object_ref(*widgets[i]);
-			gtk_container_remove(GTK_CONTAINER(gtk_widget_get_parent(*widgets[i])), *widgets[i]);
+			widget = widgets[i];
+			g_object_ref(widget);
+			gtk_container_remove(GTK_CONTAINER(gtk_widget_get_parent(*widget)), *widget);
 			i++;
-		}
-		
+		} while (widget);
```
Comment (b4n) [inline debugger/src/tpage.c:157]: I'd rather see it as
```c
for (i = 0; widgets[i]; i++)
{
	GtkWidget **widget_ref = widgets[i];
	g_object_ref(*widget_ref);
	gtk_container_remove(…);
}
```

It's more idiomatic and understandable to me than relying on the variable set in the loop.

File: debugger/src/tpage.c [hunk 2]
```diff
@@ -266,11 +267,12 @@ void tpage_pack_widgets(gboolean tabbed)
...
 	{
 		int i = 0;
-		while (widgets[i])
+		do
 		{
+			widget = widgets[i];
 			g_object_unref(*widgets[i]);
 			i++;
-		}
+		} while (widget);
```
Comment (b4n) [inline debugger/src/tpage.c:275]: what's the point here?  You're not using the variable you set in the loop.

**Review by b4n — CHANGES_REQUESTED** [review]
OK, so it's a bug in cppckeck that gets operator priority wrong, right?  Because the code was right, `*array[i]` is `*(array[i])`, not `(*array)[i]`.

Anyway, I think there could be a better loop, and there's at least an issue with the `g_object_ref()` calls.

File: debugger/src/tpage.c [hunk 3]
```diff
@@ -139,22 +139,23 @@ void tpage_pack_widgets(gboolean tabbed)
...
+
 		/* unparent widgets */
-		i = 0;
-		while (widgets[i])
+		do
 		{
-			g_object_ref(*widgets[i]);
-			gtk_container_remove(GTK_CONTAINER(gtk_widget_get_parent(*widgets[i])), *widgets[i]);
+			widget = widgets[i];
+			g_object_ref(widget);
```
[the remark this answers is not in the document]
Comment (eht16) [reply debugger/src/tpage.c]: Ouch, of course.

File: debugger/src/tpage.c (hunk 1 above)
Comment (eht16) [reply debugger/src/tpage.c]: Thanks for the idea and snippet, that's way cleaner!

File: debugger/src/tpage.c (hunk 2 above)
Comment (eht16) [reply debugger/src/tpage.c]: Being confused by rewriting the code in many variants in too short time or so.
No idea what's happened to me there...:(

**Comment by eht16** [comment]
I rewrote the code again using the `for` loop, fixed the `g_object_ref()` calls and tested again functionality and cppcheck happiness.

File: debugger/src/tpage.c [hunk 4]
```diff
@@ -142,19 +142,18 @@ void tpage_pack_widgets(gboolean tabbed)
 	GList *children = gtk_container_get_children(GTK_CONTAINER(tab_target));
 	if (children)
 	{
-		int i;
-
-		oldroot = (GtkWidget*)children->data;
+		GtkWidget **widget_ref = NULL;
```
Comment (b4n) [inline debugger/src/tpage.c:145]: I'd rather have this declared in the loop

File: debugger/src/tpage.c [hunk 5]
```diff
@@ -265,11 +264,9 @@ void tpage_pack_widgets(gboolean tabbed)
 
 	if (oldroot)
 	{
-		int i = 0;
-		while (widgets[i])
+		for (int i = 0; widgets[i]; i++)
 		{
 			g_object_unref(*widgets[i]);
```
Comment (b4n) [inline debugger/src/tpage.c:269]: Is cppcheck happy with that?  Actually I'm still confused on what it didn't like before, so maybe it's happy. It's correct anyway so whichever way's OK with me.

Comment (eht16) [reply debugger/src/tpage.c:269]: It is.
Only `gtk_container_remove(GTK_CONTAINER(gtk_widget_get_parent(*widgets[i])), *widgets[i]);` was problematic, I'm not sure why only here.

File: debugger/src/tpage.c (hunk 4 above)
Comment (eht16) [reply debugger/src/tpage.c]: Done in 516277c184f2019e2e504f1d598b008cb6695358.

File: debugger/src/tpage.c (hunk 5 above)
Comment (b4n) [reply debugger/src/tpage.c:267]: Yeah I was just testing manually building cppcheck 2.2 :)

**Review by b4n — APPROVED** [review]
LGTM, should not change any behavior, and cppcheck is happy now.

**Comment by b4n** [comment]
BTW I just tested cppcheck master and it's happy without the patch as well, so they fixed it.
Not saying this shouldn't land, it's fine a change.

**Comment by eht16** [comment]
Great and great! :)

**Comment by b4n** [comment]
Wait… nope I messed up, `master` branch is not the tip anymore, they switched to `main`.  I'll do the checking again, but I'm less optimistic that they have it fixed.

**Comment by b4n** [comment]
So it's not fixed in latest cppcheck, but that shouldn't stop merging this, quite the contrary :)
